### ISSUE TITLE
'Namespace' object has no attribute 'quiet' error after installing 0.5.6

### ISSUE THREAD

**Issue by jorritmesman** [BoldingBruggeman/parsac#6]
I just installed Parsac version 0.5.6, but when I tried to run for example `parsac sensitivity sample...`, I get the following error:
```
Reading configuration from config_sa.xml...
Traceback (most recent call last):
  File "c:\users\jorri\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\jorri\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jorri\AppData\Local\Programs\Python\Python38-32\Scripts\parsac.exe\__main__.py", line 7, in <module>
  File "c:\users\jorri\appdata\local\programs\python\python38-32\lib\site-packages\parsac\parsac_run.py", line 12, in main
    parsac.main()
  File "c:\users\jorri\appdata\local\programs\python\python38-32\lib\site-packages\parsac\__init__.py", line 48, in main
    args.func(args)
  File "c:\users\jorri\appdata\local\programs\python\python38-32\lib\site-packages\parsac\sensitivity.py", line 179, in main
    current_job = job.fromConfigurationFile(args.xmlfile, verbose=not args.quiet)
AttributeError: 'Namespace' object has no attribute 'quiet'
```

I installed parsac with `pip install parsac` (without "--user", as then it would end up in a different folder as all my other packages). My old parsac setup (first 0.5.4, then the version from Tobias' github) worked. 

I work on a Windows 10 computer, and use Python 3.8.

**Comment by jornbr** [comment]
Hi Jorrit, thanks for reporting this, I can confirm this was an issue for parsac sensitivity analysis, specifically the "sample" and "analysis" steps. I've now hopefully fixed it. Can you try installing the latest version, 0.5.7 (e.g., "pip install parsac --user")?

Cheers,

Jorn

**Comment by jorritmesman** [comment]
Yes, it works now! Thanks for the quick fix Jorn!
